name: Dependency Check

on: [push,pull_request]

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depeendency-check
    permissions:
       id-token: write
       contents: read
       security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files in the workspace
        run: |
          ls ${{ github.workspace }}
      - name: Depcheck - SARIF
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck-SARIF
        with:
          project: 'test'
          path: '.'
          format: 'SARIF'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          # args: >
          #   --enableExperimental
          #   --scan Podfile.lock
      - name: Depcheck - HTML
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck-HTML
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          # args: >
          #   --enableExperimental
          #   --scan Podfile.lock
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
      # Upload the SARIF file to Github, so the findings show up in "Security / Code Scanning alerts"
      - name: Upload Dependency Check report to CodeQL
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{github.workspace}}/reports/dependency-check-report.sarif
