# name: Produce a Gradle SBOM

# on: [push,pull_request]

# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@master

#       - name: SBOM-Action
#         uses: anchore/sbom-action@v0
#         with:
#           path: ./
